[toolchain]

[features]
resolution = true
skip-lint = false

[programs.devnet]
tbw_yaminogemu = "F3WVtr1yzW5dsYPLSvBKqF4LwD48YbcXYDjG74TxBFL6"

[registry]
url = "devnet"

[provider]
cluster = "Devnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
